# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    app.hand_size: 10

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Application\Port\RandomizerInterface:
        class: App\Infrastructure\Random\PhpRandomizer

    App\Application\Port\DeckFactoryInterface:
        class: App\Application\Service\DeckFactory

    App\Application\Port\HandSorterInterface:
        class: App\Application\Service\HandSorter

    App\Application\Port\OrderGeneratorInterface:
        class: App\Application\Service\RandomOrderGenerator

    App\UI\Console\DealCardsCommand:
        arguments:
            $defaultHandSize: '%app.hand_size%'

    App\UI\Http\CardsController:
        arguments:
            $handSize: '%app.hand_size%'
